M10_CS_AspNet_Assignments/M10_W1_Assignment1_MockDB/Controllers/CoursesController.cs
using M10_W1_Assignment1_MockDB.Data;
using M10_W1_Assignment1_MockDB.Data.Interface;
using M10_W1_Assignment1_MockDB.ModelsDto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace M10_W1_Assignment1_MockDB.Controllers {
    public class CoursesController : Controller {
        private readonly ICourseRepo _repository;
        private readonly IStudentRepo _studentRepository; //read only field
        private readonly Mapper _mapper = new Mapper();

        public CoursesController(ICourseRepo repo, IStudentRepo stuRepo) {
            _repository = repo;
            _studentRepository = stuRepo;
        }
        // GET: CoursesController
        public ActionResult Index() {
            var courseDtos = _repository.GetAllCourses()
            .Select(p => _mapper.Map(p));
            return View(courseDtos);
        }

        // GET: CoursesController/Details/5
        public ActionResult Details(int id) {
            return View();
        }

        public ActionResult StudentHTML() {
            var students = _studentRepository.GetAllStudents();
            ViewBag.students = _studentRepository;

            //view

            return View();
        }

        // GET: CoursesController/Create
        public ActionResult Create() {
            return View();
        }

        // POST: CoursesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseDto input) {
            try {
                //use mapper to save the input to db
                var courseToDb = _mapper.Map(input);
                _repository.CreateCourse(courseToDb);

                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }

        // GET: CoursesController/Edit/5
        public ActionResult Edit(int id) {
            return View();
        }

        // POST: CoursesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }

        // GET: CoursesController/Delete/5
        public ActionResult Delete(int id) {
            return View();
        }

        // POST: CoursesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }
    }
}

M10_CS_AspNet_Assignments/M10_W1_Assignment1_MockDB/Controllers/InstructorsController.cs
using M10_W1_Assignment1_MockDB.Data;
using M10_W1_Assignment1_MockDB.Data.Interface;
using M10_W1_Assignment1_MockDB.ModelsDto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace M10_W1_Assignment1_MockDB.Controllers {
    public class InstructorsController : Controller {
        private readonly IInstructorRepo _repository;
        private readonly Mapper _mapper = new Mapper();

        public InstructorsController(IInstructorRepo repo) {
            _repository = repo; 
        }
        // GET: InstructorController
        public ActionResult Index() {
            var instructorDtos = _repository.GetAllInstructors()
            .Select(p => _mapper.Map(p));
            return View(instructorDtos);
            
        }

        // GET: InstructorController/Details/5
        public ActionResult Details(int id) {
            return View();
        }

        // GET: InstructorController/Create
        public ActionResult Create() {
            return View();
        }

        // POST: InstructorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InstructorDto input) {
            try {
                //use mapper to save the input to db
                var instructorToDb = _mapper.Map(input);
                _repository.CreateInstructor(instructorToDb);

                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }

        // GET: InstructorController/Edit/5
        public ActionResult Edit(int id) {
            return View();
        }

        // POST: InstructorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }

        // GET: InstructorController/Delete/5
        public ActionResult Delete(int id) {
            return View();
        }

        // POST: InstructorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }
    }
}

M10_CS_AspNet_Assignments/M10_W1_Assignment1_MockDB/Controllers/StudentsController.cs
using M10_W1_Assignment1_MockDB.Data;
using M10_W1_Assignment1_MockDB.Data.Interface;
using M10_W1_Assignment1_MockDB.ModelsDto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace M10_W1_Assignment1_MockDB.Controllers {
    public class StudentsController : Controller {

        private readonly IStudentRepo _repository;
        private readonly ICourseRepo _courseRepo;
        private readonly Mapper _mapper = new Mapper();
        StudentDto studentDto = new StudentDto();

        //StudentsController obj = (new JavascriptSerializer()).Deserialize<StudentsController>(objJson);

        public StudentsController(IStudentRepo repo, ICourseRepo courseRepo) {
            _repository = repo;
            _courseRepo = courseRepo;

        }

        public List<string> GetStudentsByCourseId(int id) {
            var counter = 1;
            var res = _repository.GetAllStudents()                
                        .Where(p => p.courseID == id)
                        .Select(p => counter++ + ") " +  p.lastName + ", " + p.firstName  + " (Student ID: " + p.stuID + ")" + "<br> --------------- <br>")
                        .ToList();
            if (res == null || res.Count() == 0) {
                return new List<string> { "No Students in this class" };
            }

            return res;
        }

        // GET: InstructorController
        public ActionResult Index() {
            var studentDtos = _repository.GetAllStudents()
            .Select(p => _mapper.Map(p));
            return View(studentDtos);
        }

        // GET: StudentsController/Details/5
        public ActionResult Details(int id) {
            return View();
        }

        // GET: StudentsController/Create
        public ActionResult Create() {
            var courses = _courseRepo.GetAllCourses();
            ViewBag.Courses = new SelectList(courses, "courseID", "courseName");

            return View();
        }

        // POST: StudentsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentDto input) {
            try {
                //use mapper to save the input to db
                var studentToDb = _mapper.Map(input);
                _repository.CreateStudent(studentToDb);

                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }

        // GET: StudentsController/Edit/5
        public ActionResult Edit(int id) {
            var courses = _courseRepo.GetAllCourses();
            ViewBag.Courses = new SelectList(courses, "courseID", "courseName");

            return View();
        }

        // POST: StudentsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, StudentDto input) {
            try {
                //use mapper to save the input to db
                var studentToDb = _mapper.Map(input);
                _repository.UpdateStudent(studentToDb);

                return RedirectToAction(nameof(Index));
                //return View();
            }
            catch {
                return View();
            }
        }

        // GET: StudentsController/Delete/5
        public ActionResult Delete(int id) {
            return View();
        }

        // POST: StudentsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            }
            catch {
                return View();
            }
        }
    }
}

M10_CS_AspNet_Assignments/M10_W1_Assignment1_MockDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - M10_W1_Assignment1_MockDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Course Registration Program</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructors" asp-action="Index">Instructors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - M10_W1_Assignment1_MockDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src ="~/js/sharedScript.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>